# Ansible Inventory File
# This file tells Ansible about our servers and how to group them

# =============================================================================
# SERVER GROUPS
# =============================================================================
# Each group contains servers that share a role in our architecture.
# The names in brackets [like_this] are group names we can reference in playbooks.

# The openvpn server
[openvpn]
scp-openvpn-01 ansible_host=10.10.10.104

[client]
blue-win-01 ansible_host=10.10.10.41
blue-win-02 ansible_host=10.10.10.42
blue-win-03 ansible_host=10.10.10.43
blue-win-04 ansible_host=10.10.10.44
blue-lin-01 ansible_host=10.10.10.45
blue-lin-02 ansible_host=10.10.10.46
blue-lin-03 ansible_hsot=10.10.10.47
blue-lin-04 ansible_host=10.10.10.48
blue-lin-05 ansible_host=10.10.10.49


# =============================================================================
# VARIABLES FOR ALL SERVERS
# =============================================================================
# These settings apply to every server in the inventory

[all:vars]
# The username and password to connect with
ansible_user=cyberrange
ansible_password=Cyberrange123!
openvpn_port=1194
openvpn_proto=udp
tls_min=1.0
tls_max=1.0
openvpn_server_ip=10.10.10.104
openvpn_client_dir=/etc/openvpn/client
openvpn_client_name=client1



# Use password authentication (disable SSH key requirement)
ansible_ssh_pass={{ ansible_password }}


# Tell Ansible where Python is on the remote servers
ansible_python_interpreter=/usr/bin/python3

# Connect through the CyberRange jump host
ansible_ssh_common_args=-o StrictHostKeyChecking=no
